MVCECommerceProject.MVC/Areas/Customer/Controllers/ProductController.cs
using MVCECommerceProject.MODEL.Entities;
using MVCECommerceProject.MVC.Filters.AuthorizationFilters;
using MVCECommerceProject.SERVICE.Option;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace MVCECommerceProject.MVC.Areas.Customer.Controllers
{
    [CustomerAuthFilter]
    public class ProductController : Controller
    {
        private ProductService productService = new ProductService();
        public ActionResult Index()
        {
            TempData.Keep();
            if (TempData["User"] == null || TempData["UserImg"] == null)
            {
                var userDetail = Session["CLogin"] as AppUser;
                TempData["User"] = userDetail.Name + " " + userDetail.SurName;
                TempData["UserImg"] = userDetail.ImagePath;
            }
            var products = productService.GetActive();

            return View(products);
        }

        public ActionResult CustomerProducts()
        {
            var userDetail = Session["CLogin"] as AppUser;
            TempData.Keep();
            if (TempData["User"] == null || TempData["UserImg"] == null)
            {
                TempData["User"] = userDetail.Name + " " + userDetail.SurName;
                TempData["UserImg"] = userDetail.ImagePath;
            }

            var products = productService.FindCustomerProducts(userDetail.ID);

            return View(products);
        }

        public ActionResult Details(Guid id)
        {
            TempData.Keep();
            if (TempData["User"] == null || TempData["UserImg"] == null)
            {
                var userDetail = Session["CLogin"] as AppUser;
                TempData["User"] = userDetail.Name + " " + userDetail.SurName;
                TempData["UserImg"] = userDetail.ImagePath;
            }

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = productService.GetById(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        public ActionResult FindCategoryProducts(Guid id)
        {
            TempData.Keep();
            if (TempData["User"] == null || TempData["UserImg"] == null)
            {
                var userDetail = Session["CLogin"] as AppUser;
                TempData["User"] = userDetail.Name + " " + userDetail.SurName;
                TempData["UserImg"] = userDetail.ImagePath;
            }

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            List<Product> products = productService.FindCategoryActivedProducts(id).ToList();
            if (products == null)
            {
                return HttpNotFound();
            }
            return View(products);
        }

        public ActionResult FindSubCategoryProducts(Guid id)
        {
            TempData.Keep();
            if (TempData["User"] == null || TempData["UserImg"] == null)
            {
                var userDetail = Session["CLogin"] as AppUser;
                TempData["User"] = userDetail.Name + " " + userDetail.SurName;
                TempData["UserImg"] = userDetail.ImagePath;
            }

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            List<Product> products = productService.FindSubCategoryActivedProducts(id).ToList();
            if (products == null)
            {
                return HttpNotFound();
            }
            return View(products);
        }

        public ActionResult FindSellerProducts(Guid id)
        {
            var userDetail = Session["CLogin"] as AppUser;
            TempData.Keep();
            if (TempData["User"] == null || TempData["UserImg"] == null)
            {

                TempData["User"] = userDetail.Name + " " + userDetail.SurName;
                TempData["UserImg"] = userDetail.ImagePath;
            }
            var products = productService.FindSellerActivedProducts(id);
            return View(products);
        }
    }
}

MVCECommerceProject.MVC/Areas/Customer/Controllers/SellerController.cs
using MVCECommerceProject.MODEL.Entities;
using MVCECommerceProject.MVC.Filters.AuthorizationFilters;
using MVCECommerceProject.SERVICE.Option;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCECommerceProject.MVC.Areas.Customer.Controllers
{
    [CustomerAuthFilter]
    public class SellerController : Controller
    {
        private AppUserService seller = new AppUserService();
        private ProductService proser = new ProductService();

        public ActionResult Index()
        {
            TempData.Keep();
            if (TempData["User"] == null || TempData["UserImg"] == null)
            {
                var userDetail = Session["CLogin"] as AppUser;
                TempData["User"] = userDetail.Name + " " + userDetail.SurName;
                TempData["UserImg"] = userDetail.ImagePath;
            }

            var sellers = seller.GetActive().Where(x => x.Role == MODEL.Enums.Role.Seller_Customer);
            return View(sellers);
        }

        public ActionResult Find(Guid id)
        {
            TempData.Keep();
            if (TempData["User"] == null || TempData["UserImg"] == null)
            {
                var userDetail = Session["CLogin"] as AppUser;
                TempData["User"] = userDetail.Name + " " + userDetail.SurName;
                TempData["UserImg"] = userDetail.ImagePath;
            }
            var sel = seller.GetById(id);
            //TODO: Satıcı sayfası düzenlenecek
            return View(sel);
        }

        public ActionResult Products(Guid id)
        {
            TempData.Keep();
            if (TempData["User"] == null || TempData["UserImg"] == null)
            {
                var userDetail = Session["CLogin"] as AppUser;
                TempData["User"] = userDetail.Name + " " + userDetail.SurName;
                TempData["UserImg"] = userDetail.ImagePath;
            }
            var pro = proser.GetActive().Where(x => x.SellerID == id);

            return View(pro);
        }

        public ActionResult TableProducts(Guid id)
        {
            TempData.Keep();
            if (TempData["User"] == null || TempData["UserImg"] == null)
            {
                var userDetail = Session["CLogin"] as AppUser;
                TempData["User"] = userDetail.Name + " " + userDetail.SurName;
                TempData["UserImg"] = userDetail.ImagePath;
            }
            var pro = proser.GetActive().Where(x => x.SellerID == id);

            return View(pro);
        }
    }
}

MVCECommerceProject.MVC/Areas/Seller/Controllers/AccountController.cs
using MVCECommerceProject.MODEL.Entities;
using MVCECommerceProject.MVC.Filters.AuthorizationFilters;
using MVCECommerceProject.SERVICE.Option;
using System;
using System.Web;
using System.Web.Mvc;

namespace MVCECommerceProject.MVC.Areas.Seller.Controllers
{
    public class AccountController : Controller
    {
        private AppUserService db = new AppUserService();
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(AppUser model)
        {
            try
            {
                if (model.Password != null && model.Email != string.Empty)
                {
                    if (db.CheckEmpoyeeUsers(model.Email, model.Password, MODEL.Enums.Role.Seller_Customer))
                    {
                        var user = db.GetByDefault(x => x.Email == model.Email);
                        Session["SLogin"] = user;

                        var userDetail = Session["SLogin"] as AppUser;
                        TempData["User"] = userDetail.Name + " " + userDetail.SurName;
                        TempData["UserImg"] = userDetail.ImagePath;
                        TempData.Keep();
                        return RedirectToAction("Index", "Home");
                    }
                    else
                    {
                        TempData["Error"] = "Lüften E-Posta Adresiniz ve/veya Şifrenizi Kontrol Ediniz ve/veya Yekiniz Yok";
                    }
                }
                else
                {
                    TempData["Error"] = "Lütfen alanları boş bırakmayın";
                }
            }
            catch (Exception exp)
            {
                TempData["Error"] = exp.Message;
            }
            return RedirectToAction("Login");
        }

        public ActionResult ForgotPassword()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ForgotPassword(string mail)
        {
            if (!db.ForgotPassword(mail, out string errorMsg))
            {
                TempData["Error"] = errorMsg;
                return RedirectToAction("ForgotPassword");
            }

            return View();
        }

        [SellerAuthFilter]
        public ActionResult Index()
        {
            Guid id = Guid.Empty;
            if (TempData["User"] == null || TempData["UserImg"] == null)
            {
                var userDetail = Session["SLogin"] as AppUser;
                TempData["User"] = userDetail.Name + " " + userDetail.SurName;
                TempData["UserImg"] = userDetail.ImagePath;
                id = userDetail.ID;
                TempData.Keep();
            }
            else
            {
                var userDetail = Session["SLogin"] as AppUser;
                id = userDetail.ID;
            }

            return View(db.GetById(id));
        }

        [SellerAuthFilter]
        public ActionResult Edit(Guid id)
        {
            TempData.Keep();
            if (TempData["User"] == null || TempData["UserImg"] == null)
            {
                var userDetail = Session["SLogin"] as AppUser;
                TempData["User"] = userDetail.Name + " " + userDetail.SurName;
                TempData["UserImg"] = userDetail.ImagePath;
            }

            if (id != null)
            {
                AppUser appUser = db.GetById(id);
                return View(appUser);
            }
            else
            {
                TempData["Error"] = "Bir hata meydana geldi.";
                return RedirectToAction("Index");
            }
        }

        [SellerAuthFilter]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(HttpPostedFileBase ImagePath, AppUser appUser)
        {
            TempData.Keep();
            var userDetail = Session["SLogin"] as AppUser;
            if (TempData["User"] == null || TempData["UserImg"] == null)
            {
                TempData["User"] = userDetail.Name + " " + userDetail.SurName;
                TempData["UserImg"] = userDetail.ImagePath;
            }

            appUser.ModifiedBy = userDetail.Email;

            if (db.CheckAgainEmailAddres(appUser, out string msgMail, out AppUser appMailUserout))
            {
                TempData["Error"] = msgMail;
                return View(appMailUserout);
            }

            if (db.CheckAgainUserChangeTCNO(appUser, out string msgTCNO, out AppUser appTCNOUserout))
            {
                TempData["Error"] = msgTCNO;
                return View(appTCNOUserout);
            }

            db.CheckImageFullEmpty(appUser, userDetail.ImagePath, ImagePath);
            return RedirectToAction("Index");
        }

        [SellerAuthFilter]
        public ActionResult Logout()
        {
            Session.Remove("SLogin");
            TempData.Clear();

            return RedirectToAction("Login");
        }

        [SellerAuthFilter]
        public ActionResult LogChange()
        {
            var userDetail = Session["SLogin"] as AppUser;
            if (userDetail.Role == MODEL.Enums.Role.Seller_Customer)
            {
                Session["CLogin"] = Session["SLogin"] as AppUser;
                Session.Remove("SLogin");
                TempData.Clear();

                return RedirectToAction("Index", "Home", new { area = "Customer" });
            }
            return RedirectToAction("Index", "Home");
        }
    }
}

MVCECommerceProject.MVC/Areas/Seller/Controllers/CategoryController.cs
using MVCECommerceProject.MODEL.Entities;
using MVCECommerceProject.MVC.Filters.AuthorizationFilters;
using MVCECommerceProject.SERVICE.Option;
using System.Collections.Generic;
using System.Web.Mvc;

namespace MVCECommerceProject.MVC.Areas.Seller.Controllers
{
    [SellerAuthFilter]
    public class CategoryController : Controller
    {
        private CategoryService categoryService = new CategoryService();
        private SubCategoryService subCategoryService = new SubCategoryService();
        public ActionResult Index()
        {
            TempData.Keep();
            if (TempData["User"] == null || TempData["UserImg"] == null)
            {
                var userDetail = Session["SLogin"] as AppUser;
                TempData["User"] = userDetail.Name + " " + userDetail.SurName;
                TempData["UserImg"] = userDetail.ImagePath;
            }

            List<Category> kategoriler = new List<Category>();

            foreach (var item in categoryService.GetActive())
            {
                Category category = new Category();
                category = item;

                kategoriler.Add(category);
            }
            ViewData["CategoryList"] = kategoriler;

            return View(subCategoryService.GetAll());
        }
    }
}

MVCECommerceProject.MVC/Controllers/BuyController.cs
using MVCECommerceProject.COMMON.MyTools;
using MVCECommerceProject.MODEL.CartModel;
using MVCECommerceProject.MODEL.Entities;
using MVCECommerceProject.SERVICE.Option;
using System;
using System.Web.Mvc;

namespace MVCECommerceProject.MVC.Controllers
{
    public class BuyController : Controller
    {
        private ProductService productService = new ProductService();
        private OrderService orderService = new OrderService();
        private AppUserService userService = new AppUserService();
        public ActionResult SepeteEkle(Guid id)
        {
            //if (id == null)
            //{
            //    TempData["Error"] = "Lütfen, ürünü seçin!";
            //    return RedirectToAction("Index", "Home");
            //}

            var pro = productService.GetById(id);
            ViewBag.Stock = pro.UnitsInStock.ToString();

            return View(pro);
        }

        [HttpPost]
        public ActionResult SepeteEkle(Product product)
        {
            Cart c = Session["scart"] == null ? new Cart() : Session["scart"] as Cart;
            CartItem ci = new CartItem();
            ci.Quantity = product.UnitsInStock;  /*Convert.ToInt16(product.UnitPrice);*/

            var UnitsInStock = productService.GetById(product.ID).UnitsInStock;
            var ii = UnitsInStock - ci.Quantity;

            if (ci.Quantity < 0 || product.UnitsInStock <= 0)
            {
                TempData["Error"] = "Lütfen, (0) sıfırdan büyük bir sayı giriniz!";
                return View(product);
            }

            if (ii <= 0)
            {
                ci.Quantity = UnitsInStock;
                product.UnitsInStock = 0;
                product.Status = CORE.Enums.Status.Deleted;
                MailSender.SendEmail(userService.GetById(product.SellerID).Email, product.ProductName + " " + "ürünü stokta olmadığından satıştan kaldırılmıştır!!!", "Stokta Ürün Kalmadı!!!");
                if (ii < 0)
                {
                    TempData["Error"] = ii.ToString().Replace('-', ' ') + " adet satın almak istediğiniz ürün, stok miktarımızıdan fazla olduğu için sepetinize eksik olarak eklenmiştir.";
                }
            }
            else
            {
                product.UnitsInStock = Convert.ToInt16(ii);
            }

            ci.ID = product.ID;
            ci.Name = product.ProductName;
            ci.Price = product.UnitPrice;
            ci.ImagePath = product.ImagePath;
            ci.SellerID = product.SellerID;
            ci.SellerName = userService.GetById(ci.SellerID).Name + " " + userService.GetById(ci.SellerID).SurName;
            productService.Update(product);
            c.AddItem(ci);
            Session["scart"] = c;

            return RedirectToAction("Index");
        }

        public ActionResult Index()
        {
            Cart c = Session["scart"] as Cart;

            if (c == null)
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                //TODO: Satıcı adı listelenecek
                return View(c.MyCart);
            }
        }
    }
}

MVCECommerceProject.MVC/Areas/Customer/Views/Seller/Index.cshtml
@model IEnumerable<MVCECommerceProject.MODEL.Entities.AppUser>
@{
    ViewBag.Title = "Tüm Satıcılarımız";
    Layout = "~/Areas/Customer/Views/Shared/_Layout.cshtml";
}

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">@ViewBag.Title</h6>
        @Html.ActionLink("Tüm Ürünler", "Index", "Product", null, new { @class = "pull-right-mycss" })
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.ImagePath)
                        </th>
                        <th>
                            Satıcı Adı ve Soyadı
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Email)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.PhoneNumber)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Address)
                        </th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.ImagePath)
                        </th>
                        <th>
                            Satıcı Adı ve Soyadı
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Email)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.PhoneNumber)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Address)
                        </th>
                    </tr>
                </tfoot>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                <img class="img-sm-mycss"
                                     src="@item.ImagePath">
                            </td>
                            <td>
                                <a href="@Url.Action("Find", "Seller", new { area = "Customer", id = item.ID })">
                                    @item.Name @item.SurName
                                </a>
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Email)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.PhoneNumber)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Address)
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

MVCECommerceProject.MVC/Areas/Customer/Views/Seller/Products.cshtml
@model IEnumerable<MVCECommerceProject.MODEL.Entities.Product>
@{
    ViewBag.Title = "Tüm Ürünlerim";
    Layout = "~/Areas/Customer/Views/Shared/_Layout.cshtml";
}

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">@ViewBag.Title - @TempData["User"] Hoşgeldiniz</h6>
    </div>
    <div class="card-body">
        <div class="d-sm-flex align-items-center m-lg-auto">
            @foreach (var item in Model)
            {
                <div class="card shadow mb-2">
                    <!-- Card Header - Accordion -->
                    <a href="#collapseCardExample-@item.ProductName" class="d-block card-header py-3" data-toggle="collapse"
                       role="button" aria-expanded="true" aria-controls="collapseCardExample">
                        <h6 class="m-0 font-weight-bold text-primary">@item.ProductName</h6>
                    </a>
                    <!-- Card Content - Collapse -->
                    <div class="collapse show" id="collapseCardExample-@item.ProductName">
                        <div class="card-body">
                            <img class="img-lm-mycss"
                                 src="@item.ImagePath">

                            <br />
                            <p>
                                @Html.ActionLink("Kategori: " + item.SubCategory.Category.Name, "FindCategoryProducts", "Product", new { id = item.SubCategory.CategoryID }, new { @class = "" })
                            </p>
                            <p>
                                @Html.ActionLink("Alt Kategori: " + item.SubCategory.Name, "FindSubCategoryProducts", "Product", new { id = item.SubCategory.ID }, new { @class = "" })
                            </p>
                            <p>
                                @Html.ActionLink("Satıcı: " + item.Seller.Name + " " + item.Seller.SurName, "FindSellerProducts", "Product", new { id = item.SellerID }, new { @class = "" })
                            </p>

                            @Html.ActionLink("Sepete Ekle", "SepeteEkle", "Buy", new { id = item.ID }, new { @class = "btn btn-lg btn-block btn-success" })
                            @Html.ActionLink("Hemen Satın Al", "Index", "Buy", new { id = item.ID }, new { @class = "btn btn-lg btn-block btn-success" })
                        </div>
                    </div>
                </div>
                <div>
                    <br />
                </div>
            }
        </div>
    </div>
</div>

MVCECommerceProject.MVC/Areas/Customer/Views/Seller/TableProducts.cshtml
@model IEnumerable<MVCECommerceProject.MODEL.Entities.Product>
@{
    ViewBag.Title = "Tüm Ürünlerim (Tablo)";
    Layout = "~/Areas/Customer/Views/Shared/_Layout.cshtml";
}

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">@ViewBag.Title</h6>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.ImagePath)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.ProductName)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.UnitPrice)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.UnitsInStock)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.SubCategory.Category.Name)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.SubCategory.Name)
                        </th>
                        <th>
                            Satıcı
                        </th>
                        <th>
                            Sepete Ekle | Hemen Satın Al
                        </th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.ImagePath)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.ProductName)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.UnitPrice)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.UnitsInStock)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.SubCategory.Category.Name)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.SubCategory.Name)
                        </th>
                        <th>
                            Satıcı
                        </th>
                        <th>
                            Sepete Ekle | Hemen Satın Al
                        </th>
                    </tr>
                </tfoot>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                <img class="img-sm-mycss"
                                     src="@item.ImagePath">
                            </td>
                            <td>
                                <a href="@Url.Action("Details", "Product", new { area = "Customer", id = item.ID })">
                                    @item.ProductName
                                </a>
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.UnitPrice)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.UnitsInStock)
                            </td>
                            <td>
                                <a href="@Url.Action("FindCategoryProducts", "Product", new { area = "Customer", id = item.SubCategory.CategoryID })">
                                    @item.SubCategory.Category.Name
                                </a>
                            </td>
                            <td>
                                <a href="@Url.Action("FindSubCategoryProducts", "Product", new { area = "Customer", id = item.SubCategory.ID })">
                                    @item.SubCategory.Name
                                </a>
                            </td>
                            <td>
                                <a href="@Url.Action("Find", "Seller", new { area = "Customer", id = item.SellerID })">
                                    @item.Seller.Name @item.Seller.SurName
                                </a>
                            </td>
                            <td>
                                @Html.ActionLink("Sepete Ekle", "SepeteEkle", "Buy", new { area = "Customer", id = item.ID }, new { @class = "" }) |
                                @Html.ActionLink("Hemen Satın Al", "FastBuy", "Buy", new { area = "Customer", id = item.ID }, new { @class = "" })
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>