MVCECommerceProject.MVC/Areas/Customer/Controllers/OrderController.cs
using MVCECommerceProject.MODEL.Entities;
using MVCECommerceProject.MVC.Filters.AuthorizationFilters;
using MVCECommerceProject.SERVICE.Option;
using System;
using System.Data;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace MVCECommerceProject.MVC.Areas.Customer.Controllers
{
    [CustomerAuthFilter]
    public class OrderController : Controller
    {
        private OrderService ors = new OrderService();
        private OrderDetailService ords = new OrderDetailService();

        public ActionResult Index()
        {
            var userDetail = Session["CLogin"] as AppUser;
            TempData.Keep();
            if (TempData["User"] == null || TempData["UserImg"] == null)
            {

                TempData["User"] = userDetail.Name + " " + userDetail.SurName;
                TempData["UserImg"] = userDetail.ImagePath;
            }

            return View(ords.GetActive().Where(x => x.Order.CustomerID == userDetail.ID));
        }

        public ActionResult OrderDetails(Guid id)
        {
            TempData.Keep();
            if (TempData["User"] == null || TempData["UserImg"] == null)
            {
                var userDetail = Session["CLogin"] as AppUser;
                TempData["User"] = userDetail.Name + " " + userDetail.SurName;
                TempData["UserImg"] = userDetail.ImagePath;
            }

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = ors.GetById(id);

            //TODO: Yeni eklene siparişte ürün adı null geliyor.
            //TODO: Sipariş detay sayfası düzenlenecek.
            if (order == null)
            {
                return HttpNotFound();
            }

            return View(order);
        }
    }
}

MVCECommerceProject.MVC/Areas/Customer/Controllers/SellerController.cs
using MVCECommerceProject.MODEL.Entities;
using MVCECommerceProject.MVC.Filters.AuthorizationFilters;
using MVCECommerceProject.SERVICE.Option;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCECommerceProject.MVC.Areas.Customer.Controllers
{
    [CustomerAuthFilter]
    public class SellerController : Controller
    {
        private AppUserService seller = new AppUserService();
        private ProductService proser = new ProductService();

        public ActionResult Index()
        {
            TempData.Keep();
            if (TempData["User"] == null || TempData["UserImg"] == null)
            {
                var userDetail = Session["CLogin"] as AppUser;
                TempData["User"] = userDetail.Name + " " + userDetail.SurName;
                TempData["UserImg"] = userDetail.ImagePath;
            }

            var sellers = seller.GetActive().Where(x => x.Role == MODEL.Enums.Role.Seller_Customer);
            return View(sellers);
        }

        public ActionResult Find(Guid id)
        {
            TempData.Keep();
            if (TempData["User"] == null || TempData["UserImg"] == null)
            {
                var userDetail = Session["CLogin"] as AppUser;
                TempData["User"] = userDetail.Name + " " + userDetail.SurName;
                TempData["UserImg"] = userDetail.ImagePath;
            }
            var sel = seller.GetById(id);
            //TODO: Satıcı sayfası düzenlenecek
            return View(sel);
        }

        public ActionResult Products(Guid id)
        {
            TempData.Keep();
            if (TempData["User"] == null || TempData["UserImg"] == null)
            {
                var userDetail = Session["CLogin"] as AppUser;
                TempData["User"] = userDetail.Name + " " + userDetail.SurName;
                TempData["UserImg"] = userDetail.ImagePath;
            }
            var pro = proser.GetActive().Where(x => x.SellerID == id);

            return View(pro);
        }

        public ActionResult TableProducts(Guid id)
        {
            TempData.Keep();
            if (TempData["User"] == null || TempData["UserImg"] == null)
            {
                var userDetail = Session["CLogin"] as AppUser;
                TempData["User"] = userDetail.Name + " " + userDetail.SurName;
                TempData["UserImg"] = userDetail.ImagePath;
            }
            var pro = proser.GetActive().Where(x => x.SellerID == id);

            return View(pro);
        }
    }
}

MVCECommerceProject.MVC/Controllers/ProductController.cs
using MVCECommerceProject.MODEL.Entities;
using MVCECommerceProject.SERVICE.Option;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace MVCECommerceProject.MVC.Controllers
{
    public class ProductController : Controller
    {
        private ProductService productService = new ProductService();

        public ActionResult Index()
        {
            var products = productService.GetActive();
            return View(products);
        }

        public ActionResult Details(Guid id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = productService.GetById(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        public ActionResult FindCategoryProducts(Guid id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            List<Product> products = productService.FindCategoryActivedProducts(id).ToList();
            if (products == null)
            {
                return HttpNotFound();
            }
            return View(products);
        }

        public ActionResult FindSubCategoryProducts(Guid id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            List<Product> products = productService.FindSubCategoryActivedProducts(id).ToList();
            if (products == null)
            {
                return HttpNotFound();
            }
            return View(products);
        }

        public ActionResult FindSellerProducts(Guid id)
        {
            var products = productService.FindSellerActivedProducts(id);
            return View(products);
        }
    }
}

MVCECommerceProject.MVC/Areas/Customer/Views/Shared/PartialViews/Sidebar/_OthersMenusSidebar.cshtml
@if (TempData["User"] != null)
{
<li class="nav-item">
    <a class="nav-link" href="@Url.Action("Index", "Order")">
        <i class="fas fa-fw fa-shopping-bag"></i>
        <span>Siparişlerim</span>
    </a>
</li>
}

MVCECommerceProject.MVC/Areas/Customer/Views/Shared/PartialViews/Sidebar/_ProductsSellersSidebar.cshtml
<li class="nav-item">
    <a class="nav-link" href="@Url.Action("Index", "Product")">
        <i class="fas fa fa-shopping-bag fa-sm fa-fw mr-2 text-gray-400"></i>
        <span>Tüm Ürünler</span>
    </a>
</li>

<li class="nav-item">
    <a class="nav-link" href="@Url.Action("Index", "Seller")">
        <i class="fas fa fa-users fa-sm fa-fw mr-2 text-gray-400"></i>
        <span>Tüm Satıcılar</span>
    </a>
</li>

MVCECommerceProject.MVC/Areas/Customer/Views/Shared/PartialViews/Sidebar/_Sidebar.cshtml
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="@Url.Action("Index","Home")">
        <div class="sidebar-brand-icon rotate-n-15">
            <i class="fas fa-laugh-wink"></i>
        </div>
        <div class="sidebar-brand-text mx-3">E-ticaret</div>
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <!-- Nav Item - Dashboard -->
    <li class="nav-item active">
        <a class="nav-link" href="@Url.Action("Index","Home")">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>E-ticaret</span>
        </a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <li class="nav-item">
        <a class="nav-link" href="@Url.Action("Index","Home")">
            <i class="fas fa-fw fa-table"></i>
            <span>Anasayfa</span>
        </a>
    </li>

    @Html.Partial("PartialViews/Sidebar/_OthersMenusSidebar")

    @Html.Partial("PartialViews/Sidebar/_ProductsSellersSidebar")

    @Html.Partial("PartialViews/Sidebar/_LoginSidebar")

    @Html.Partial("PartialViews/Sidebar/_ContactAboutSidebar")

    @Html.Partial("PartialViews/Sidebar/_LogoutSidebar")

    <!-- Divider -->
    <hr class="sidebar-divider d-none d-md-block">

    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>
</ul>